// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as Css from "bs-css/lib/es6/src/Css.js";
import * as Block from "bs-platform/lib/es6/block.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Belt_Option from "bs-platform/lib/es6/belt_Option.js";
import * as Router$ReasonCarousel from "./Router.bs.js";
import * as ReactTransitionGroup from "react-transition-group";

var app = Css.style(/* :: */[
      Css.minHeight(Css.vh(100)),
      /* :: */[
        Css.after(/* :: */[
              Css.contentRule(""),
              /* :: */[
                Css.transitions(/* :: */[
                      /* `transition */[
                        -659583595,
                        "opacity 450ms cubic-bezier(0.23, 1, 0.32, 1)"
                      ],
                      /* :: */[
                        /* `transition */[
                          -659583595,
                          "transform 0ms cubic-bezier(0.23, 1, 0.32, 1) 450ms"
                        ],
                        /* [] */0
                      ]
                    ]),
                /* :: */[
                  Css.position(Css.fixed),
                  /* :: */[
                    Css.top(Css.zero),
                    /* :: */[
                      Css.right(Css.zero),
                      /* :: */[
                        Css.bottom(Css.zero),
                        /* :: */[
                          Css.left(Css.zero),
                          /* :: */[
                            Css.backgroundColor(Css.rgba(0, 0, 0, 0.33)),
                            /* :: */[
                              Css.transform(Css.translateX(Css.pct(-100))),
                              /* :: */[
                                Css.opacity(0),
                                /* :: */[
                                  Css.zIndex(1),
                                  /* [] */0
                                ]
                              ]
                            ]
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]),
        /* :: */[
          Css.selector("&.overlay", /* :: */[
                Css.after(/* :: */[
                      /* `transition */[
                        -659583595,
                        "opacity 450ms cubic-bezier(0.23, 1, 0.32, 1)"
                      ],
                      /* :: */[
                        Css.transform(Css.translateX(Css.zero)),
                        /* :: */[
                          Css.opacity(1),
                          /* [] */0
                        ]
                      ]
                    ]),
                /* [] */0
              ]),
          /* :: */[
            Css.selector("> header", /* :: */[
                  Css.display(Css.flexBox),
                  /* :: */[
                    Css.alignItems(Css.center),
                    /* :: */[
                      Css.height(Css.px(60)),
                      /* :: */[
                        Css.backgroundColor(Css.dodgerblue),
                        /* :: */[
                          Css.color(Css.white),
                          /* :: */[
                            Css.boxShadows(/* :: */[
                                  /* `shadow */[
                                    488687584,
                                    "0 4px 5px 0 rgba(15, 74, 133, 0.14)"
                                  ],
                                  /* :: */[
                                    /* `shadow */[
                                      488687584,
                                      "0 2px 9px 1px rgba(15, 74, 133, 0.12)"
                                    ],
                                    /* :: */[
                                      /* `shadow */[
                                        488687584,
                                        "0 4px 2px -2px rgba(15, 74, 133, 0.2)"
                                      ],
                                      /* [] */0
                                    ]
                                  ]
                                ]),
                            /* :: */[
                              Css.selector("> a", /* :: */[
                                    Css.display(Css.flexBox),
                                    /* :: */[
                                      Css.alignItems(Css.center),
                                      /* :: */[
                                        Css.width(Css.px(32)),
                                        /* :: */[
                                          Css.height(Css.pct(100)),
                                          /* :: */[
                                            Css.padding2(Css.zero, Css.px(10)),
                                            /* :: */[
                                              Css.cursor(/* pointer */-786317123),
                                              /* :: */[
                                                Css.selector("> img", /* :: */[
                                                      Css.width(Css.pct(100)),
                                                      /* :: */[
                                                        Css.height(Css.pct(100)),
                                                        /* [] */0
                                                      ]
                                                    ]),
                                                /* [] */0
                                              ]
                                            ]
                                          ]
                                        ]
                                      ]
                                    ]
                                  ]),
                              /* :: */[
                                Css.selector("> h1", /* :: */[
                                      Css.fontSize(Css.px(26)),
                                      /* :: */[
                                        Css.lineHeight(Css.px(26)),
                                        /* :: */[
                                          Css.marginLeft(Css.px(10)),
                                          /* [] */0
                                        ]
                                      ]
                                    ]),
                                /* [] */0
                              ]
                            ]
                          ]
                        ]
                      ]
                    ]
                  ]
                ]),
            /* :: */[
              Css.selector("> nav", /* :: */[
                    /* `transition */[
                      -659583595,
                      "transform 450ms cubic-bezier(0.23, 1, 0.32, 1)"
                    ],
                    /* :: */[
                      Css.position(Css.absolute),
                      /* :: */[
                        Css.top(Css.zero),
                        /* :: */[
                          Css.left(Css.zero),
                          /* :: */[
                            Css.transform(Css.translateX(/* `calc */[
                                      -1044768619,
                                      /* tuple */[
                                        /* sub */5745024,
                                        Css.pct(-100),
                                        Css.px(10)
                                      ]
                                    ])),
                            /* :: */[
                              Css.height(Css.vh(100)),
                              /* :: */[
                                Css.backgroundColor(Css.white),
                                /* :: */[
                                  Css.boxShadows(/* :: */[
                                        /* `shadow */[
                                          488687584,
                                          "rgba(0, 0, 0, 0.16) 0px 3px 10px"
                                        ],
                                        /* :: */[
                                          /* `shadow */[
                                            488687584,
                                            "rgba(0, 0, 0, 0.23) 0px 3px 10px"
                                          ],
                                          /* [] */0
                                        ]
                                      ]),
                                  /* :: */[
                                    Css.overflow(Css.auto),
                                    /* :: */[
                                      Css.zIndex(2),
                                      /* :: */[
                                        Css.selector("&.active", /* :: */[
                                              Css.transform(Css.translateX(Css.zero)),
                                              /* [] */0
                                            ]),
                                        /* :: */[
                                          Css.selector("> label", /* :: */[
                                                Css.fontWeight(Css.normal),
                                                /* :: */[
                                                  Css.fontSize(Css.px(12)),
                                                  /* :: */[
                                                    Css.lineHeight(Css.px(24)),
                                                    /* :: */[
                                                      Css.textTransform(Css.uppercase),
                                                      /* :: */[
                                                        Css.display(Css.block),
                                                        /* :: */[
                                                          Css.backgroundColor(Css.rgba(0, 0, 0, 0.32)),
                                                          /* :: */[
                                                            Css.color(Css.white),
                                                            /* :: */[
                                                              Css.padding2(Css.zero, Css.px(15)),
                                                              /* [] */0
                                                            ]
                                                          ]
                                                        ]
                                                      ]
                                                    ]
                                                  ]
                                                ]
                                              ]),
                                          /* :: */[
                                            Css.selector("> header", /* :: */[
                                                  Css.position(Css.relative),
                                                  /* :: */[
                                                    Css.backgroundColor(Css.lavender),
                                                    /* :: */[
                                                      Css.height(Css.px(150)),
                                                      /* :: */[
                                                        Css.margin(Css.zero),
                                                        /* :: */[
                                                          Css.selector("> a", /* :: */[
                                                                Css.fontSize(Css.px(24)),
                                                                /* :: */[
                                                                  Css.lineHeight(Css.px(24)),
                                                                  /* :: */[
                                                                    Css.position(Css.absolute),
                                                                    /* :: */[
                                                                      Css.top(Css.zero),
                                                                      /* :: */[
                                                                        Css.left(Css.zero),
                                                                        /* :: */[
                                                                          Css.display(Css.flexBox),
                                                                          /* :: */[
                                                                            Css.alignItems(Css.center),
                                                                            /* :: */[
                                                                              Css.height(Css.px(40)),
                                                                              /* :: */[
                                                                                Css.padding2(Css.px(10), Css.px(20)),
                                                                                /* :: */[
                                                                                  Css.selector("> img", /* :: */[
                                                                                        Css.width(Css.px(20)),
                                                                                        /* :: */[
                                                                                          Css.height(Css.px(20)),
                                                                                          /* :: */[
                                                                                            Css.marginRight(Css.px(20)),
                                                                                            /* [] */0
                                                                                          ]
                                                                                        ]
                                                                                      ]),
                                                                                  /* [] */0
                                                                                ]
                                                                              ]
                                                                            ]
                                                                          ]
                                                                        ]
                                                                      ]
                                                                    ]
                                                                  ]
                                                                ]
                                                              ]),
                                                          /* [] */0
                                                        ]
                                                      ]
                                                    ]
                                                  ]
                                                ]),
                                            /* :: */[
                                              Css.selector("> ul", /* :: */[
                                                    Css.margin(Css.zero),
                                                    /* :: */[
                                                      Css.padding(Css.zero),
                                                      /* :: */[
                                                        Css.listStyleType(Css.none),
                                                        /* :: */[
                                                          Css.selector("> li", /* :: */[
                                                                Css.position(Css.relative),
                                                                /* :: */[
                                                                  Css.borderBottom(Css.px(1), Css.solid, Css.rgba(0, 0, 0, 0.06)),
                                                                  /* :: */[
                                                                    Css.after(/* :: */[
                                                                          Css.unsafe("content", "url('./img/icon/chevron.svg')"),
                                                                          /* :: */[
                                                                            Css.position(Css.absolute),
                                                                            /* :: */[
                                                                              Css.top(Css.zero),
                                                                              /* :: */[
                                                                                Css.right(Css.px(15)),
                                                                                /* :: */[
                                                                                  Css.bottom(Css.zero),
                                                                                  /* :: */[
                                                                                    Css.margin(Css.auto),
                                                                                    /* :: */[
                                                                                      Css.width(Css.px(15)),
                                                                                      /* :: */[
                                                                                        Css.height(Css.px(15)),
                                                                                        /* [] */0
                                                                                      ]
                                                                                    ]
                                                                                  ]
                                                                                ]
                                                                              ]
                                                                            ]
                                                                          ]
                                                                        ]),
                                                                    /* :: */[
                                                                      Css.selector("> a", /* :: */[
                                                                            /* `transition */[
                                                                              -659583595,
                                                                              "background-color 450ms cubic-bezier(0.23, 1, 0.32, 1)"
                                                                            ],
                                                                            /* :: */[
                                                                              Css.fontSize(Css.px(18)),
                                                                              /* :: */[
                                                                                Css.lineHeight(Css.px(54)),
                                                                                /* :: */[
                                                                                  Css.textDecoration(Css.none),
                                                                                  /* :: */[
                                                                                    Css.display(Css.block),
                                                                                    /* :: */[
                                                                                      Css.padding2(Css.zero, Css.px(15)),
                                                                                      /* :: */[
                                                                                        Css.color(Css.black),
                                                                                        /* :: */[
                                                                                          Css.selector("&.active", /* :: */[
                                                                                                Css.backgroundColor(Css.hex("e9e9e9")),
                                                                                                /* [] */0
                                                                                              ]),
                                                                                          /* [] */0
                                                                                        ]
                                                                                      ]
                                                                                    ]
                                                                                  ]
                                                                                ]
                                                                              ]
                                                                            ]
                                                                          ]),
                                                                      /* :: */[
                                                                        Css.selector("> img", /* :: */[
                                                                              Css.width(Css.px(15)),
                                                                              /* :: */[
                                                                                Css.height(Css.px(15)),
                                                                                /* [] */0
                                                                              ]
                                                                            ]),
                                                                        /* [] */0
                                                                      ]
                                                                    ]
                                                                  ]
                                                                ]
                                                              ]),
                                                          /* [] */0
                                                        ]
                                                      ]
                                                    ]
                                                  ]),
                                              /* :: */[
                                                Css.media("(max-width: 767px)", /* :: */[
                                                      Css.width(Css.vw(85)),
                                                      /* [] */0
                                                    ]),
                                                /* :: */[
                                                  Css.media("(min-width: 768px)", /* :: */[
                                                        Css.width(Css.px(300)),
                                                        /* [] */0
                                                      ]),
                                                  /* [] */0
                                                ]
                                              ]
                                            ]
                                          ]
                                        ]
                                      ]
                                    ]
                                  ]
                                ]
                              ]
                            ]
                          ]
                        ]
                      ]
                    ]
                  ]),
              /* [] */0
            ]
          ]
        ]
      ]
    ]);

var Styles = /* module */[/* app */app];

function App(Props) {
  var currentRoute = Props.currentRoute;
  var navRef = React.useRef(null);
  var match = navRef.current;
  var width = (match == null) ? 0.0 : match.clientWidth;
  var match$1 = React.useReducer((function (state, action) {
          if (typeof action === "number") {
            if (state[/* isOpen */0]) {
              var match = Belt_Option.getWithDefault(state[/* touches */1][/* first */0], /* tuple */[
                    0.0,
                    0.0
                  ]);
              var match$1 = Belt_Option.getWithDefault(state[/* touches */1][/* last */1], /* tuple */[
                    0.0,
                    0.0
                  ]);
              var x$prime = match$1[0];
              var velocity = (x$prime - match[0]) / (match$1[1] - match[1]);
              var state_000 = /* isOpen */state[/* isOpen */0];
              var state_001 = /* touches : record */[
                /* first */undefined,
                /* last */undefined
              ];
              var state$1 = /* record */[
                state_000,
                state_001
              ];
              if (velocity < -0.3 || x$prime < width / 2.0) {
                return /* record */[
                        /* isOpen */false,
                        /* touches : record */[
                          /* first */undefined,
                          /* last */undefined
                        ]
                      ];
              } else {
                return state$1;
              }
            } else {
              return state;
            }
          } else {
            switch (action.tag | 0) {
              case 0 : 
                  return /* record */[
                          /* isOpen */action[0],
                          /* touches */state[/* touches */1]
                        ];
              case 1 : 
                  if (state[/* isOpen */0]) {
                    return /* record */[
                            /* isOpen */state[/* isOpen */0],
                            /* touches : record */[
                              /* first *//* tuple */[
                                action[0],
                                performance.now()
                              ],
                              /* last */undefined
                            ]
                          ];
                  } else {
                    return state;
                  }
              case 2 : 
                  if (state[/* isOpen */0]) {
                    var init = state[/* touches */1];
                    return /* record */[
                            /* isOpen */state[/* isOpen */0],
                            /* touches : record */[
                              /* first */init[/* first */0],
                              /* last *//* tuple */[
                                action[0],
                                performance.now()
                              ]
                            ]
                          ];
                  } else {
                    return state;
                  }
              
            }
          }
        }), /* record */[
        /* isOpen */false,
        /* touches : record */[
          /* first */undefined,
          /* last */undefined
        ]
      ]);
  var dispatch = match$1[1];
  var state = match$1[0];
  React.useEffect((function () {
          var handler = function (param) {
            return Curry._1(dispatch, /* ToggleMenu */Block.__(0, [false]));
          };
          addEventListener("popstate", handler);
          return (function (param) {
                    removeEventListener("popstate", handler);
                    return /* () */0;
                  });
        }));
  var match$2 = state[/* isOpen */0];
  var match$3 = state[/* isOpen */0];
  var match$4 = state[/* touches */1];
  var match$5 = match$4[/* first */0];
  var tmp;
  var exit = 0;
  if (match$5 !== undefined) {
    var match$6 = match$4[/* last */1];
    if (match$6 !== undefined) {
      var x$prime = match$6[0];
      var x = match$5[0];
      var match$7 = x$prime - x > 0.0;
      tmp = {
        transition: "none",
        transform: "translateX(" + ((
              match$7 ? 0.0 : x$prime - x
            ).toString() + "0px)")
      };
    } else {
      exit = 1;
    }
  } else {
    exit = 1;
  }
  if (exit === 1) {
    tmp = { };
  }
  return React.createElement("div", {
              className: "App " + (app + (
                  match$2 ? " overlay" : ""
                )),
              onClick: (function (_event) {
                  if (state[/* isOpen */0]) {
                    return Curry._1(dispatch, /* ToggleMenu */Block.__(0, [false]));
                  } else {
                    return 0;
                  }
                }),
              onTouchEnd: (function (_event) {
                  return Curry._1(dispatch, /* TouchEnd */0);
                }),
              onTouchMove: (function ($$event) {
                  return Curry._1(dispatch, /* TouchMove */Block.__(2, [$$event.changedTouches.item(0).clientX]));
                }),
              onTouchStart: (function ($$event) {
                  return Curry._1(dispatch, /* TouchStart */Block.__(1, [$$event.changedTouches.item(0).clientX]));
                })
            }, React.createElement("header", undefined, React.createElement("a", {
                      onClick: (function ($$event) {
                          $$event.stopPropagation();
                          return Curry._1(dispatch, /* ToggleMenu */Block.__(0, [true]));
                        })
                    }, React.createElement("img", {
                          src: (require("../../../src/img/icon/hamburger.svg"))
                        })), React.createElement("h1", undefined, currentRoute[/* title */1])), React.createElement("nav", {
                  ref: navRef,
                  className: match$3 ? "active" : "",
                  style: tmp,
                  onClick: (function ($$event) {
                      $$event.stopPropagation();
                      return /* () */0;
                    })
                }, React.createElement("header", undefined, React.createElement("a", {
                          onClick: (function (_event) {
                              return Curry._1(dispatch, /* ToggleMenu */Block.__(0, [false]));
                            })
                        }, React.createElement("img", {
                              src: (require("../../../src/img/icon/arrow.svg"))
                            }), currentRoute[/* title */1])), React.createElement("label", undefined, "home"), React.createElement("ul", undefined, React.createElement("li", undefined, React.createElement(Router$ReasonCarousel.NavLink[/* make */0], {
                              href: "/",
                              children: "Home"
                            }))), React.createElement("label", undefined, "pages"), React.createElement("ul", undefined, React.createElement("li", undefined, React.createElement(Router$ReasonCarousel.NavLink[/* make */0], {
                              href: "/page1",
                              children: "Page1"
                            })), React.createElement("li", undefined, React.createElement(Router$ReasonCarousel.NavLink[/* make */0], {
                              href: "/page2",
                              children: "Page2"
                            })), React.createElement("li", undefined, React.createElement(Router$ReasonCarousel.NavLink[/* make */0], {
                              href: "/page3",
                              children: "Page3"
                            })))), React.createElement("main", undefined, React.createElement(ReactTransitionGroup.TransitionGroup, {
                      children: React.createElement(ReactTransitionGroup.CSSTransition, {
                            in: true,
                            timeout: 900,
                            classNames: "routeTransition",
                            children: currentRoute[/* component */2],
                            key: currentRoute[/* title */1]
                          })
                    })));
}

var make = App;

export {
  Styles ,
  make ,
  
}
/* app Not a pure module */
