// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as Css from "bs-css/lib/es6/src/Css.js";
import * as React from "react";
import * as ReactDOMRe from "reason-react/lib/es6/src/ReactDOMRe.js";
import * as App$ReasonCarousel from "./App.bs.js";
import * as Router$ReasonCarousel from "./Router.bs.js";

Css.$$global("body", /* :: */[
      Css.margin(Css.zero),
      /* :: */[
        Css.fontFamily("Helvetica, Arial, sans-serif"),
        /* [] */0
      ]
    ]);

Css.$$global("h1, h2, h3", /* :: */[
      Css.fontWeight(/* normal */812216871),
      /* [] */0
    ]);

Css.$$global("img", /* :: */[
      Css.display(/* block */888960333),
      /* :: */[
        Css.maxWidth(Css.pct(100)),
        /* [] */0
      ]
    ]);

Css.$$global("a", /* :: */[
      Css.cursor(/* pointer */-786317123),
      /* [] */0
    ]);

var Styles = /* module */[];

ReactDOMRe.renderToElementWithId(React.createElement(Router$ReasonCarousel.WithRouter[/* make */0], {
          children: (function (currentRoute) {
              return React.createElement(App$ReasonCarousel.make, {
                          currentRoute: currentRoute
                        });
            })
        }), "root");

export {
  Styles ,
  
}
/*  Not a pure module */
